remote_theme: jekyll/minima@d4d779a
#
# Minima requires the following plugins:
plugins:
 - jekyll-feed
 - jekyll-seo-tag

minima:
  skin: dark

  nav_pages:
    - swaps.md
    

  social_links:
    - title: Numista
      icon: coins
      url: "https://en.numista.com/echanges/profil.php?id=557968"
    - title: ebay listings
      icon: ebay
      url: "https://www.ebay.com.au/usr/monty124au"

  hide_site_feed_link: true

